language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: heaper@gmail.com
  api_key:
    secure: tlI6hBUOMvyIFqobLAJTTVfwVh0M2gs6uPHn1R2cYV99pDr8ymF8WtFUTMcascnUZ5ujqExKQn74pYTwRy2SZJsJQiavTeSE27sVYktNceZPof5WL0LLxeBOssxFL12M5Oz47wuNEj/CR9oNq1k7ax6eo/9aDWOS6VvhmwOVm8mfGyUKUOwqx22B6/Xub2q2ApHAxVxI1pr+aL3k2XL+eMZHp6FuBR+DS6Z/hgPlLFKqsk4q9bcDlrXQfCfzRBxFbP4XtC/4PdA9p86kd3eIouVPDRqI+i4DMZB0+K7wMeK8l3YfaAPW2vssnQKFLFF8Rgt5SUAU+0axX0HUDSIIal7oeJKFWjOlhM/N6ugtFZAdsZFNL/hQ/GPQ22oFqICD3xZpzchPbzQODp3XIjQcu//aAc/+x0sCzeGbsO+EN0rWMUfztEQoeR8RFwnNIcbrXbP6s6UquCZXvI98cONxuu3rW0uOUQB811LUZpf26DsQv7dS1YWFu8a/dVO8yW62QwqrFfLPxAUEBBWUiT8z735jT2Tu+HIkq7j25j4IBMSrcQAwp3zu1qC7ISypmSbjG8d5QaavjFV7m4j8uwHdDWnbERIZTJonzQcMgFiIczB9SaBAt4Pq3Gfel8llxYEkFxns7qYSdX6s+E7MkVH6239yLb5YSdRvYMtApCcMG2M=
  on:
    branch: master
    tags: true
    repo: DEGJS/easing
